In [11]:
#패키지 불러오기
import pandas as pd
import numpy as np
from sklearn import model_selection
from sklearn import metrics
import matplotlib.pyplot as pit
from sklearn import datasets
from sklearn.tree import DecisionTreeClassifier

# 1.데이터 수집

In [12]:
#데이터프레임으로 데이터 읽어오기
df = pd.read_csv("iris.csv", index_col='Id')
print(df.shape)
df.head()

#여기서 Y는 Species 임

(100, 5)


SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
Id                                                                       
1             5.1           3.5            1.4           0.2  Iris-setosa
2             4.9           3.0            1.4           0.2  Iris-setosa
3             4.7           3.2            1.3           0.2  Iris-setosa
4             4.6           3.1            1.5           0.2  Iris-setosa
5             5.0           3.6            1.4           0.2  Iris-setosa

# 2. 데이터 전처리

In [13]:
df["Species"] = df.Species.map({"Iris-setosa":1,"Iris-versicolor":0})
df

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
Id                                                                    
1              5.1           3.5            1.4           0.2        1
2              4.9           3.0            1.4           0.2        1
3              4.7           3.2            1.3           0.2        1
4              4.6           3.1            1.5           0.2        1
5              5.0           3.6            1.4           0.2        1
..             ...           ...            ...           ...      ...
96             5.7           3.0            4.2           1.2        0
97             5.7           2.9            4.2           1.3        0
98             6.2           2.9            4.3           1.3        0
99             5.1           2.5            3.0           1.1        0
100            5.7           2.8            4.1           1.3        0

[100 rows x 5 columns]

In [14]:
X = np.array(df.iloc[:,0:4])
Y = np.array(df['Species'])

In [15]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [16]:
Y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

# 3. 모델 적합

In [17]:
#모델 적합
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=0)
print("X_train 크기:", X_train.shape)
print("y_train 크기:", Y_train.shape)
print("X_test 크기:", X_test.shape)
print("y_test 크기:", Y_test.shape)

X_train 크기: (70, 4)
y_train 크기: (70,)
X_test 크기: (30, 4)
y_test 크기: (30,)


In [18]:
from sklearn.tree import DecisionTreeClassifier

#fit 는 적합시킨다는 의미 (학습시킬 때는 train 만 씀)
tree = DecisionTreeClassifier(random_state=0) #max_depth 미지정
tree.fit(X_train, Y_train)

DecisionTreeClassifier(random_state=0)

# 4. 모델 성능평가

In [19]:
#4. 모델 성능평가
temp_y_pred = tree.predict(X_test)
print("예측값\n", temp_y_pred)
print("실제값\n", Y_test)

예측값
 [1 0 1 0 0 0 1 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 1 0 1 1 1 0 0 0]
실제값
 [1 0 1 0 0 0 1 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 1 0 1 1 1 0 0 0]


In [20]:
#정확도 계산
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
temp_acc = accuracy_score(Y_test, temp_y_pred)
print('정확도: ', format(temp_acc))

정확도:  1.0
