# 원핫인코딩

## 60170029 이종언

In [25]:
import pandas as pd
import numpy as np

# 1. 원핫인코딩

In [26]:
dfs = pd.DataFrame({'season':['Spring','Summer','Fall','Winter',np.nan]})
dfs

season
0  Spring
1  Summer
2    Fall
3  Winter
4     NaN

## 1-1) season 행의 값들을 칼럼으로 만들기

In [27]:
print(dfs['season'])
pd.get_dummies(dfs['season'])

0    Spring
1    Summer
2      Fall
3    Winter
4       NaN
Name: season, dtype: object


Fall  Spring  Summer  Winter
0  False    True   False   False
1  False   False    True   False
2   True   False   False   False
3  False   False   False    True
4  False   False   False   False

## 1-2) 특정 칼럼을 명시해주는 것과 아닌것의 차이

In [28]:
#df의 전체 칼럼을 대상으로 원핫인코딩 진행
pd.get_dummies(dfs)

season_Fall  season_Spring  season_Summer  season_Winter
0        False           True          False          False
1        False          False           True          False
2         True          False          False          False
3        False          False          False           True
4        False          False          False          False

In [29]:
pd.get_dummies(dfs['season'])

Fall  Spring  Summer  Winter
0  False    True   False   False
1  False   False    True   False
2   True   False   False   False
3  False   False   False    True
4  False   False   False   False

##### 차이 : 특정 칼럼 명시 시에는 그 칼럼만 더미화시킴
##### + 더미화 칼럼명칭의 계층구조가 한 단계 내려감

In [30]:
#만약 레코드에 Null값도 따로 인코딩을 하고 싶을 경우
#보통 경우에는 Null값은 무시됨

In [31]:
pd.get_dummies(dfs['season'], dummy_na=True)

Fall  Spring  Summer  Winter    NaN
0  False    True   False   False  False
1  False   False    True   False  False
2   True   False   False   False  False
3  False   False   False    True  False
4  False   False   False   False   True

# 2. 원핫인코딩 연습

### student.csv 의 nationality 변수 인코딩

In [32]:
df1 = pd.read_csv('student.csv')
df1.head()

gre   gpa  rank sex  age nationality admission
0  380.0  3.61     3   f   19       Korea       불합격
1  660.0  3.67     3   f   18       Korea       NaN
2  800.0  4.00     1   m   19       Korea        합격
3    NaN  3.19     4   m   19       Korea        합격
4  520.0  2.93     4   f   19       Korea       불합격

### get_dummies 칼럼 지정법에 따른 차이

In [33]:
pd.get_dummies(df1['nationality']).head()

China  India  Japan  Korea  Mongol  Vietnam
0  False  False  False   True   False    False
1  False  False  False   True   False    False
2  False  False  False   True   False    False
3  False  False  False   True   False    False
4  False  False  False   True   False    False

# 더미화 후 기존 데이터프레임에 붙이기

In [34]:
pd.get_dummies(df1, columns = ['nationality']).head()

gre   gpa  rank sex  age admission  nationality_China  nationality_India   
0  380.0  3.61     3   f   19       불합격              False              False  \
1  660.0  3.67     3   f   18       NaN              False              False   
2  800.0  4.00     1   m   19        합격              False              False   
3    NaN  3.19     4   m   19        합격              False              False   
4  520.0  2.93     4   f   19       불합격              False              False   

   nationality_Japan  nationality_Korea  nationality_Mongol   
0              False               True               False  \
1              False               True               False   
2              False               True               False   
3              False               True               False   
4              False               True               False   

   nationality_Vietnam  
0                False  
1                False  
2                False  
3                False  
4                False

## 2-1) nationality 칼럼으로 인코딩 진행

In [35]:
df1 = pd.get_dummies(df1, columns = ['nationality'])

In [36]:
df1.head(10)

gre   gpa  rank sex  age admission  nationality_China  nationality_India   
0  380.0  3.61     3   f   19       불합격              False              False  \
1  660.0  3.67     3   f   18       NaN              False              False   
2  800.0  4.00     1   m   19        합격              False              False   
3    NaN  3.19     4   m   19        합격              False              False   
4  520.0  2.93     4   f   19       불합격              False              False   
5  760.0  3.00     2   f   19        합격              False              False   
6  560.0  2.98     1   m   19        합격              False              False   
7  400.0  3.08     2   f   19       불합격              False              False   
8  540.0  3.39     3   m   19        합격              False              False   
9  700.0  3.92     2   m   19       불합격              False              False   

   nationality_Japan  nationality_Korea  nationality_Mongol   
0              False               True               False  \
1              False               True               False   
2              False               True               False   
3              False               True               False   
4              False               True               False   
5              False               True               False   
6              False               True               False   
7              False               True               False   
8              False               True               False   
9              False               True               False   

   nationality_Vietnam  
0                False  
1                False  
2                False  
3                False  
4                False  
5                False  
6                False  
7                False  
8                False  
9                False

# 실습 #1)

# 3) 타이타닉 데이터에서 탑승 항구 변수를 인코딩하기

### 3-1) 타이타닉 데이터 불러오기

In [37]:
df_titanic = pd.read_csv('titanic.csv')
#매핑
df_titanic["Sex"] = df_titanic.Sex.map({"male":1,"female":0})
df_titanic["Embarked"] = df_titanic.Embarked.map({"S":0,"C":1,"Q":2})
#단, 인코딩할 Embarked 속성은 Drop 하지 않음
df_titanic = df_titanic.drop(['Name', 'Ticket', 'Cabin'],axis=1)
df_titanic.head(5)

PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0            1         0       3    1  22.0      1      0   7.2500       0.0
1            2         1       1    0  38.0      1      0  71.2833       1.0
2            3         1       3    0  26.0      0      0   7.9250       0.0
3            4         1       1    0  35.0      1      0  53.1000       0.0
4            5         0       3    1  35.0      0      0   8.0500       0.0

### 3-2) 결측치 확인 및 결측치 보간

In [38]:
df_titanic.Age.fillna(df_titanic.Age.median(), inplace=True)
df_titanic.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       2
dtype: int64

##### Embarked 의 Null값 제거

In [39]:
df_titanic = df_titanic.dropna(subset='Embarked')
df_titanic.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
dtype: int64

##### 결측치 없음

## 3-3) 원핫인코딩

In [40]:
#인코딩 이전과 비교하기 위한 백업
dfbkup = df_titanic.copy()

In [41]:
df_titanic = pd.get_dummies(df_titanic, columns = ['Embarked'])
df_titanic

PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare   
0              1         0       3    1  22.0      1      0   7.2500  \
1              2         1       1    0  38.0      1      0  71.2833   
2              3         1       3    0  26.0      0      0   7.9250   
3              4         1       1    0  35.0      1      0  53.1000   
4              5         0       3    1  35.0      0      0   8.0500   
..           ...       ...     ...  ...   ...    ...    ...      ...   
886          887         0       2    1  27.0      0      0  13.0000   
887          888         1       1    0  19.0      0      0  30.0000   
888          889         0       3    0  28.0      1      2  23.4500   
889          890         1       1    1  26.0      0      0  30.0000   
890          891         0       3    1  32.0      0      0   7.7500   

     Embarked_0.0  Embarked_1.0  Embarked_2.0  
0            True         False         False  
1           False          True         False  
2            True         False         False  
3            True         False         False  
4            True         False         False  
..            ...           ...           ...  
886          True         False         False  
887          True         False         False  
888          True         False         False  
889         False          True         False  
890         False         False          True  

[889 rows x 11 columns]

In [42]:
#[원핫인코딩 이후 데이터프레임]
X = np.array(df_titanic.iloc[:,2:]) 
Y = np.array(df_titanic['Survived'])
#[원핫인코딩 이전 데이터프레임]
X1 = np.array(dfbkup.iloc[:,2:]) 
Y1 = np.array(dfbkup['Survived']) 

In [43]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=0)
X1_train, X1_test, Y1_train, Y1_test = train_test_split(X1, Y1, test_size=0.3, random_state=0)

tree = DecisionTreeClassifier(random_state=12345)
tree1 = DecisionTreeClassifier(random_state=12345)

tree.fit(X_train, Y_train)
tree1.fit(X1_train, Y1_train)

print('[원핫인코딩 이후 모델 생성]')
print(classification_report(Y_test, tree.predict(X_test)))
print(confusion_matrix(Y_test, tree.predict(X_test)))

print('[원핫인코딩 없이 모델 생성]')
print(classification_report(Y1_test, tree1.predict(X1_test)))
print(confusion_matrix(Y1_test, tree1.predict(X1_test)))

[원핫인코딩 이후 모델 생성]
              precision    recall  f1-score   support

           0       0.79      0.80      0.80       157
           1       0.71      0.70      0.71       110

    accuracy                           0.76       267
   macro avg       0.75      0.75      0.75       267
weighted avg       0.76      0.76      0.76       267

[[126  31]
 [ 33  77]]
[원핫인코딩 없이 모델 생성]
              precision    recall  f1-score   support

           0       0.79      0.81      0.80       157
           1       0.72      0.70      0.71       110

    accuracy                           0.76       267
   macro avg       0.76      0.75      0.76       267
weighted avg       0.76      0.76      0.76       267

[[127  30]
 [ 33  77]]


##### 정확도에서는 원핫인코딩 전후로 차이가 없었으나, macro 평균에서는 오히려 약간 정확도가 하락한 것을 보았다. 탑승 항구에 따른 생존률의 차이는 없기 떄문이다.

# 실습 #1 끝

# 4) 타이타닉 데이터에서 변수중요도 알아보기

##### 각 변수별로 Y값 결정에 대한 기여도를 수치화하여 보여줌

In [44]:
tree.feature_importances_

array([0.12265626, 0.3194374 , 0.21270503, 0.06225354, 0.03458046,
       0.2153135 , 0.00360442, 0.00911096, 0.02033843])

#### 데이터프레임으로 만들기

In [45]:
pd.DataFrame(tree.feature_importances_.reshape((1,-1)), index=['feature_importance'])

0         1         2         3        4         5   
feature_importance  0.122656  0.319437  0.212705  0.062254  0.03458  0.215313  \

                           6         7         8  
feature_importance  0.003604  0.009111  0.020338

#### 데이터프레임에 칼럼명 넣기

In [46]:
df_titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch',
       'Fare', 'Embarked_0.0', 'Embarked_1.0', 'Embarked_2.0'],
      dtype='object')

In [47]:
pd.DataFrame(tree.feature_importances_.reshape((1,-1)), columns=df_titanic.columns[2:11], index=['feature_importance'])

Pclass       Sex       Age     SibSp    Parch      Fare   
feature_importance  0.122656  0.319437  0.212705  0.062254  0.03458  0.215313  \

                    Embarked_0.0  Embarked_1.0  Embarked_2.0  
feature_importance      0.003604      0.009111      0.020338